### ISSUE TITLE
Bag transfer issues for api-v2

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/dpn-server#5]
@diamondap says, at https://internet2.slack.com/archives/i2-dpn-developers/p1472841471000477,
- [ ] 1. dpn-server should set StoreRequested to true on replication transfers when the to_node returns a good fixity value.
- [ ] 2. we should have a vocabulary for the CancelReason field of the transfer (bad fixity, bag invalid, error on replicating node, no space on replicating node, other).
- [ ] 3. possibly add a new field to ReplicationTransfer called cancel_reason_detail, where we can store free-form text describing why the transfer was cancelled.

This might be split out into separate issues.

**Comment by malakai97** [comment]
For 1, use [ActiveRecord::Observer](https://github.com/rails/rails-observers)

**Comment by darrenleeweber** [comment]
- [ ] dpn-server should set StoreRequested to true on replication transfers when the to_node returns a good fixity value.
- [ ] we should have a vocabulary for the CancelReason field of the transfer (bad fixity, bag invalid, error on replicating node, no space on replicating node, other).
- [ ] possibly add a new field to ReplicationTransfer called cancel_reason_detail, where we can store free-form text describing why the transfer was cancelled.

**Comment by dazza-codes** [comment]
This issue was moved to dpn-admin/dpn-server#61
